[root at 2023-02-26 18:53:55,092]: Archipelago (0.3.9) logging initialized on Linux-6.1.12-x64v3-xanmod1-x86_64-with-glibc2.35 running Python 3.10.6
[root at 2023-02-26 18:53:55,107]: Triggered Suboption "plando_items" of "shuffle_symbols" did not overwrite a root option. This is probably in error.
[root at 2023-02-26 18:53:55,112]: Uncaught exception
Traceback (most recent call last):
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 178, in main
    tuple(roll_settings(yaml, args.plando) for yaml in weights_cache[path])
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 178, in <genexpr>
    tuple(roll_settings(yaml, args.plando) for yaml in weights_cache[path])
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 473, in roll_settings
    handle_option(ret, game_weights, option_key, option, plando_options)
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 422, in handle_option
    player_option.verify(AutoWorldRegister.world_types[ret.game], ret.name, plando_options)
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Options.py", line 50, in verify
    f(self, *args, **kwargs)
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Options.py", line 738, in verify
    raise Exception(f"Item {item_name} from option {self} "
Exception: Item RopeDart from option StartHints(RopeDart, Wingsuit) is not a valid item name from The Messenger. Did you mean 'Rope Dart' (88% sure)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 643, in <module>
    main()
  File "/mnt/115b93af-9f3b-43c4-a778-48dcab29caf0/Randomizers/Archipelago Betas/Generate.py", line 197, in main
    raise ValueError(f"File {path} is destroyed. Please fix your yaml.") from e
ValueError: File Newsupermarcobro BT Async - Marco Barrick.yaml is destroyed. Please fix your yaml.
